title: RepreSENt
subtitle: RepreSENting SEND in Bath & NES
description: Parent-led campaign for better SEND provision in Bath and North East Somerset and neighbouring authorities.
url: "https://alicethoylesense.github.io"
baseurl: "/representsend-site"
markdown: kramdown
permalink: pretty
plugins: []
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
